//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30311.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comp2007_final {
    public partial class UrlField {
        protected global::System.Web.UI.WebControls.HyperLink HyperLinkUrl;
    }
}
