//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comp2007_final.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Raid
    {
        public Raid()
        {
            this.RaidMemebers = new HashSet<RaidMemeber>();
        }
    
        public int Id { get; set; }
        public string RaidName { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string Description { get; set; }
        public Nullable<int> NumberNeeded { get; set; }
        public Nullable<int> NumberSignedUp { get; set; }
    
        public virtual ICollection<RaidMemeber> RaidMemebers { get; set; }
    }
}
