//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comp2007_final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Raid
    {
        public Raid()
        {
            this.RaidMemebers = new HashSet<RaidMemeber>();
        }
    
        public int Id { get; set; }
        public string RaidName { get; set; }
        public string Time { get; set; }
        public string Description { get; set; }
        public Nullable<int> TanksNeeded { get; set; }
        public Nullable<int> HealersNeeded { get; set; }
        public Nullable<int> DpsNeeded { get; set; }
        public int TanksHave { get; set; }
        public int HealersHave { get; set; }
        public int DpsHave { get; set; }
    
        public virtual ICollection<RaidMemeber> RaidMemebers { get; set; }
    }
}
